---
title: "R Project 1 - Hello R"
author: "Juritza Pantoja"
date: "Due Sept 8th"
output: 
  html_document: 
    fig_width: 20
    fig_height: 20
    highlight: zenburn
    theme: paper
---


### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1
The datasaurus_dozen has 13 rows, 2 columns, and 3 variables, which are the **dataset**, **x-values**, and **y-values**.    

### Exercise 2
```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
dino_data %>%
  summarize(r = cor(x,y))
```

### Exercise 3

```{r plot-star, fig.height=3, fig.width=6}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
star_data %>%
  summarize(r = plot(x, y))
```
 
```{r cor-star, fig.height=3, fig.width=6}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
star_data %>%
  summarize(r = cor(x, y))
```

### Exercise 4

```{r cor-circle, fig.height=3, fig.width=6}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
circle_data %>%
  summarize(r = cor(x, y))

```

```{r plot-circle, fig.height=3, fig.width=6}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
circle_data %>%
  summarize(r = plot(x, y))
```

### Exercise 5
```{r cor-dataset}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) + # facet the dataset variable, in 3 cols
  theme(legend.position = "none")
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r =cor(x, y)) %>%
  print(36)
```
